# Generated by Django 3.1 on 2020-08-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_assignment_choice_gradedassignment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='story',
            field=models.TextField(max_length=1000),
        ),
    ]
