# Generated by Django 3.1 on 2020-08-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_auto_20200829_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradedassignment',
            name='assignment',
        ),
        migrations.AddField(
            model_name='gradedassignment',
            name='question',
            field=models.CharField(default='IELTS', max_length=200),
            preserve_default=False,
        ),
    ]
