# Generated by Django 3.1 on 2020-08-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0007_auto_20200831_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedassignment',
            name='asnt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
